#ifndef SMARTHOMEEMBEDDEDCORE_GLOBAL_H
#define SMARTHOMEEMBEDDEDCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SMARTHOMEEMBEDDEDCORE_LIBRARY)
#  define SMARTHOMEEMBEDDEDCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SMARTHOMEEMBEDDEDCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SMARTHOMEEMBEDDEDCORE_GLOBAL_H
